// <auto-generated />
using BookManagementSystem.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookManagementSystem.API.Migrations
{
    [DbContext(typeof(BookDbContext))]
    [Migration("20250106114422_AddGenreColumnToBook")]
    partial class AddGenreColumnToBook
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("BookManagementSystem.API.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "F. Scott Fitzgerald",
                            Genre = "Fiction",
                            Title = "The Great Gatsby",
                            Year = 1925
                        },
                        new
                        {
                            Id = 2,
                            Author = "Harper Lee",
                            Genre = "Fiction",
                            Title = "To Kill a Mockingbird",
                            Year = 1960
                        },
                        new
                        {
                            Id = 3,
                            Author = "George Orwell",
                            Genre = "Dystopian",
                            Title = "1984",
                            Year = 1949
                        },
                        new
                        {
                            Id = 4,
                            Author = "Jane Austen",
                            Genre = "Romance",
                            Title = "Pride and Prejudice",
                            Year = 1813
                        },
                        new
                        {
                            Id = 5,
                            Author = "J.D. Salinger",
                            Genre = "Fiction",
                            Title = "The Catcher in the Rye",
                            Year = 1951
                        },
                        new
                        {
                            Id = 6,
                            Author = "Herman Melville",
                            Genre = "Adventure",
                            Title = "Moby-Dick",
                            Year = 1851
                        },
                        new
                        {
                            Id = 7,
                            Author = "J.R.R. Tolkien",
                            Genre = "Fantasy",
                            Title = "The Hobbit",
                            Year = 1937
                        },
                        new
                        {
                            Id = 8,
                            Author = "Eric Ries",
                            Genre = "Business",
                            Title = "The Lean Startup",
                            Year = 2011
                        },
                        new
                        {
                            Id = 9,
                            Author = "Yuval Noah Harari",
                            Genre = "Non-Fiction",
                            Title = "Sapiens: A Brief History of Humankind",
                            Year = 2011
                        },
                        new
                        {
                            Id = 10,
                            Author = "Michelle Obama",
                            Genre = "Biography",
                            Title = "Becoming",
                            Year = 2018
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
